name: foodka_client
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  form_inputs:
    path: packages/form_inputs/

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

  # network
  dio: ^5.7.0
  talker_dio_logger: ^4.4.1

  # state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0

  intl: ^0.19.0

  # generator
  freezed_annotation: ^2.4.4
  freezed: ^2.5.7
  retrofit: ^4.3.0
  auto_route: ^9.2.2
  flutter_gen: ^5.7.0

  # ui
  fading_edge_scrollview: ^4.1.1
  lottie: ^3.1.2
  toastification: ^2.2.0
  carousel_slider_plus: ^7.0.1
  skeletonizer: ^1.4.2

  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
  share_plus: ^10.0.2
  connectivity_plus: ^6.0.5
  mask_text_input_formatter: ^2.9.0

  equatable: ^2.0.5
  formz: ^0.7.0
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.7.0
  json_serializable: ^6.8.0
  auto_route_generator: ^9.0.0

flutter_gen:
  output: lib/core/utils/gen/
  line_length: 80

  integrations:
    flutter_svg: true
  

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/tab_box/
    - assets/icons/food/
    - .env

  fonts:
    - family: YandexSans
      fonts:
        - asset: assets/fonts/yandex_sans/YandexSansDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/yandex_sans/YandexSansText-Bold.ttf
          weight: 700
        - asset: assets/fonts/yandex_sans/YandexSansDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/yandex_sans/YandexSansText-Light.ttf
          weight: 300
        - asset: assets/fonts/yandex_sans/YandexSansText-Medium.ttf
          weight: 500
        - asset: assets/fonts/yandex_sans/YandexSansDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/yandex_sans/YandexSansDisplay-RegularItalic.ttf
          weight: 400
        - asset: assets/fonts/yandex_sans/YandexSansText-Regular.ttf
          weight: 400
        - asset: assets/fonts/yandex_sans/YandexSansText-RegularItalic.ttf
          weight: 400
        - asset: assets/fonts/yandex_sans/YandexSansDisplay-Thin.ttf
          weight: 100
        - asset: assets/fonts/yandex_sans/YandexSansText-Thin.ttf
          weight: 100