name: foodka_client
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  dio: ^5.6.0

  # state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0

  intl: ^0.19.0
  easy_localization: ^3.0.7

  # generator
  freezed_annotation: ^2.4.4
  retrofit: ^4.3.0
  auto_route: ^9.2.0
  flutter_gen: ^5.7.0

  # ui
  fading_edge_scrollview: ^4.1.1
  lottie: ^3.1.2
  fluttertoast: ^8.2.6
  carousel_slider_plus: ^7.0.0
  zoom_tap_animation: ^1.1.0
  skeletonizer: ^1.4.2

  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
  share_plus: ^10.0.0
  connectivity_plus: ^6.0.5
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.7.0
  json_serializable: ^6.8.0
  freezed: ^2.5.7

flutter_gen:
  output: lib/core/utils/gen/
  line_length: 80

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/tab_box/
    - assets/icons/food/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/work_sans/WorkSans-Black.ttf
          weight: 900
        - asset: assets/fonts/work_sans/WorkSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/work_sans/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/work_sans/WorkSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/work_sans/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/work_sans/WorkSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/work_sans/WorkSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/work_sans/WorkSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/work_sans/WorkSans-Italic.ttf
          style: italic
        - asset: assets/fonts/work_sans/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/work_sans/WorkSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/work_sans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/work_sans/WorkSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/work_sans/WorkSans-Regular.ttf
        - asset: assets/fonts/work_sans/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/work_sans/WorkSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/work_sans/WorkSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/work_sans/WorkSans-ThinItalic.ttf
          weight: 100
          style: italic

