name: foodka_client
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  dio: ^5.6.0

  # state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0

  intl: ^0.19.0
  easy_localization: ^3.0.7

  # generator
  freezed_annotation: ^2.4.4
  retrofit: ^4.3.0
  auto_route: ^9.2.0
  flutter_gen: ^5.7.0

  # ui
  fading_edge_scrollview: ^4.1.1
  lottie: ^3.1.2
  fluttertoast: ^8.2.6
  carousel_slider_plus: ^7.0.0
  zoom_tap_animation: ^1.1.0
  skeletonizer: ^1.4.2

  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
  share_plus: ^10.0.0
  connectivity_plus: ^6.0.5
  mask_text_input_formatter: ^2.9.0
  talker_dio_logger: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.7.0
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  auto_route_generator: ^9.0.0

flutter_gen:
  output: lib/core/utils/gen/
  line_length: 80

  integrations:
    flutter_svg: true
  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/tab_box/
    - assets/icons/food/

  fonts:
    - family: YandexSans
      fonts:
        - asset: assets/fonts/yandex/YandexSansDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/yandex/YandexSansText-Bold.ttf
          weight: 700
        - asset: assets/fonts/yandex/YandexSansDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/yandex/YandexSansText-Light.ttf
          weight: 300
        - asset: assets/fonts/yandex/YandexSansText-Medium.ttf
          weight: 500
        - asset: assets/fonts/yandex/YandexSansDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/yandex/YandexSansDisplay-RegularItalic.ttf
          weight: 400
        - asset: assets/fonts/yandex/YandexSansText-Regular.ttf
          weight: 400
        - asset: assets/fonts/yandex/YandexSansText-RegularItalic.ttf
          weight: 400
        - asset: assets/fonts/yandex/YandexSansDisplay-Thin.ttf
          weight: 100
        - asset: assets/fonts/yandex/YandexSansText-Thin.ttf
          weight: 100

